=== k-kame1220/ficklewolf-k/spec/master/schema/attributes.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://ficklewolf.shackw.com/k/spec/master/schema/attributes.schema.json",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["id", "name", "strongAgainst", "iconKey", "bgmKey"],
    "additionalProperties": false,
    "properties": {
      "id": { "$ref": "common.schema.json#/$defs/attribute" },
      "name": { "type": "string" },
      "strongAgainst": { "$ref": "common.schema.json#/$defs/attribute" },
      "iconKey": { "$ref": "common.schema.json#/$defs/assetKey" },
      "bgmKey": { "$ref": "common.schema.json#/$defs/assetKey" }
    }
  }
}

=== k-kame1220/ficklewolf-k/spec/master/attributes.json
[
  {
    "id": "yang",
    "name": "陽",
    "strongAgainst": "note",
    "iconKey": "attributes/yang",
    "bgmKey": "bgm/battle/yang"
  },
  {
    "id": "note",
    "name": "音",
    "strongAgainst": "moon",
    "iconKey": "attributes/note",
    "bgmKey": "bgm/battle/note"
  },
  {
    "id": "moon",
    "name": "月",
    "strongAgainst": "yang",
    "iconKey": "attributes/moon",
    "bgmKey": "bgm/battle/moon"
  }
]
